In [1]:
import numpy as np
from tqdm import tqdm
import os

In [2]:
dir_name = 'matrix_3_dataset'
train_set_num = 10*10000
test_set_num = 10000
val_set_num = 10000
epsilon = 0.01
matrix_size = 3
if not os.path.isdir(dir_name):
    os.mkdir(dir_name)

base_matrix = np.zeros((matrix_size,matrix_size), dtype=np.float64)
base_matrix[0,:]=[1,1,1]
base_matrix[1,:]=[1,2,3]
base_matrix[2,:]=[1,2,4]

In [3]:
def generate_data(num, save_path, matrix_size, base_matrix, epsilon=0.01):
    temp_set = np.zeros((num,matrix_size,matrix_size,2), dtype=np.float64)
    for i in tqdm(range(num)):
        temp = np.random.rand(matrix_size,matrix_size).astype(np.float64)
        temp = temp*2-1
        # print(temp)
        cur_matrix = base_matrix + epsilon*temp
        temp_inv = np.linalg.inv(cur_matrix)
        # print(temp_inv)
    
        temp_set[i, :,:,0] = temp[:,:]
        temp_set[i, :,:,1] = temp_inv[:,:]
    
    np.save(save_path, temp_set)

In [4]:
generate_data(train_set_num, dir_name+'/'+'train_set', matrix_size, base_matrix, epsilon)

100%|██████████| 100000/100000 [00:01<00:00, 68404.82it/s]


In [5]:
generate_data(val_set_num, dir_name+'/'+'val_set', matrix_size, base_matrix, epsilon)

100%|██████████| 10000/10000 [00:00<00:00, 64764.59it/s]


In [6]:
generate_data(test_set_num, dir_name+'/'+'test_set', matrix_size, base_matrix, epsilon)

100%|██████████| 10000/10000 [00:00<00:00, 63377.69it/s]


In [7]:
np.save(dir_name+'/'+'base_matrix', base_matrix)

In [8]:
temp = np.random.rand(matrix_size,matrix_size).astype(np.float64)
temp = temp*2-1
cur_matrix = base_matrix + epsilon*temp
temp_inv = np.linalg.inv(cur_matrix)
print(temp)
print(cur_matrix)
print(temp_inv)

[[-0.58017616  0.45820231  0.40544852]
 [-0.7288362   0.80770307  0.58045493]
 [ 0.39508998 -0.57429774 -0.76527452]]
[[0.99419824 1.00458202 1.00405449]
 [0.99271164 2.00807703 3.00580455]
 [1.0039509  1.99425702 3.99234725]]
[[ 1.97418376 -1.96022953  0.97934336]
 [-0.92293746  2.89028858 -1.94395993]
 [-0.03542003 -0.95082012  0.97525161]]


In [9]:
cur_matrix = base_matrix
temp_inv = np.linalg.inv(cur_matrix)
print(temp)
print(cur_matrix)
print(temp_inv)

[[-0.58017616  0.45820231  0.40544852]
 [-0.7288362   0.80770307  0.58045493]
 [ 0.39508998 -0.57429774 -0.76527452]]
[[1. 1. 1.]
 [1. 2. 3.]
 [1. 2. 4.]]
[[ 2. -2.  1.]
 [-1.  3. -2.]
 [ 0. -1.  1.]]
