In [1]:
import numpy as np
from tqdm import tqdm

In [2]:
dir_name = 'matrix_2_dataset'
train_set_num = 100*10000
test_set_num = 10000
val_set_num = 10000
epsilon = 0.01
matrix_size = 2


base_matrix = np.zeros((matrix_size,matrix_size), dtype=np.float64)
base_matrix[0,0]=2
base_matrix[0,1]=2
base_matrix[1,0]=2
base_matrix[1,1]=3

In [3]:
def generate_data(num, save_path, matrix_size, base_matrix, epsilon=0.01):
    temp_set = np.zeros((num,matrix_size,matrix_size,2), dtype=np.float64)
    for i in tqdm(range(num)):
        temp = np.random.rand(matrix_size,matrix_size).astype(np.float64)
        temp = temp*2-1
        # print(temp)
        cur_matrix = base_matrix + epsilon*temp
        temp_inv = np.linalg.inv(cur_matrix)
        # print(temp_inv)
    
        temp_set[i, :,:,0] = temp[:,:]
        temp_set[i, :,:,1] = temp_inv[:,:]
    
    np.save(save_path, temp_set)

In [4]:
generate_data(train_set_num, dir_name+'/'+'train_set', matrix_size, base_matrix, epsilon)

100%|██████████| 1000000/1000000 [00:14<00:00, 68699.34it/s]


In [5]:
generate_data(val_set_num, dir_name+'/'+'val_set', matrix_size, base_matrix, epsilon)

100%|██████████| 10000/10000 [00:00<00:00, 65589.70it/s]


In [6]:
generate_data(test_set_num, dir_name+'/'+'test_set', matrix_size, base_matrix, epsilon)

100%|██████████| 10000/10000 [00:00<00:00, 67306.69it/s]


In [7]:
np.save(dir_name+'/'+'base_matrix', base_matrix)

In [8]:
temp = np.random.rand(matrix_size,matrix_size).astype(np.float64)
temp = temp*2-1
cur_matrix = base_matrix + epsilon*temp
temp_inv = np.linalg.inv(cur_matrix)
print(temp)
print(cur_matrix)
print(temp_inv)

[[-0.11393212  0.77369498]
 [ 0.11582734  0.14287818]]
[[1.99886068 2.00773695]
 [2.00115827 3.00142878]]
[[ 1.51461969 -1.0131701 ]
 [-1.00985029  1.00869085]]


In [9]:
cur_matrix = base_matrix
temp_inv = np.linalg.inv(cur_matrix)
print(temp)
print(cur_matrix)
print(temp_inv)

[[-0.11393212  0.77369498]
 [ 0.11582734  0.14287818]]
[[2. 2.]
 [2. 3.]]
[[ 1.5 -1. ]
 [-1.   1. ]]
