In [1]:
import numpy as np
from tqdm import tqdm
import os

In [2]:
dir_name = 'matrix_16'
matrix_size=16
if not os.path.isdir(dir_name):
    os.mkdir(dir_name)

base_matrix = np.random.randint(5, size=(16, 16))-2
inv_base_matrix = np.linalg.inv(base_matrix)


In [3]:
np.save(dir_name+'/'+'base_matrix', base_matrix)
np.save(dir_name+'/'+'inv_base_matrix', inv_base_matrix)

In [5]:
epsilon=0.01
temp = np.random.rand(matrix_size,matrix_size).astype(np.float64)
temp = temp*2-1
cur_matrix = base_matrix + epsilon*temp
temp_inv = np.linalg.inv(cur_matrix)
print(temp)
print(cur_matrix)
print(temp_inv)

[[ 0.53540973  0.34273005  0.24809131  0.75476517 -0.04641076 -0.91893365
  -0.5823719   0.84427806 -0.80241544 -0.83315266 -0.23073206  0.42809787
  -0.57951927 -0.4332215  -0.99888173  0.58768034]
 [ 0.7214893   0.17668428  0.74813441  0.44891676  0.59626347  0.15845513
  -0.81107848  0.36337541  0.31881234 -0.69558594  0.86788878  0.0118067
   0.96038849 -0.56400748 -0.14379458  0.27861512]
 [ 0.15455472 -0.22337099  0.52684693 -0.62865534 -0.94363093  0.9266417
   0.1026905   0.10901956 -0.30641895  0.60628868  0.12513575  0.86619155
   0.37102751 -0.12219372 -0.60971954  0.33373167]
 [-0.76725009 -0.96848851 -0.00867456 -0.20350732  0.47856254  0.55659462
   0.20953322 -0.48321743  0.11213536 -0.08918524  0.51759555 -0.40299632
  -0.38067147  0.74685986 -0.96496225 -0.16867978]
 [ 0.83339545  0.67970872  0.58724401  0.24237776  0.04750178  0.2030825
   0.69303717  0.34664831  0.89184276  0.30631664  0.02609189  0.05067097
  -0.70565787 -0.63982862  0.54164414 -0.37247124]
 [-0.833

In [7]:
cur_matrix = base_matrix
temp_inv = np.linalg.inv(cur_matrix)
print(cur_matrix)
print(temp_inv)

[[-1  2 -2 -2 -2  1 -2  2  0  1  1 -1  2 -2  1 -2]
 [ 2 -2 -1  0 -2  1  1  0  1  2  0  2  2  0 -1 -2]
 [-1  2  2  1  2  1 -2 -2  0  1  0  2  2  0  2 -1]
 [ 2 -1 -1  1  0  2  1  2  1  0  1  2  2 -2 -2  2]
 [ 1  0 -1  1 -1  0  1 -1  0  0 -1  2  2 -2  2 -1]
 [ 0 -1  0  0  1 -2  2 -2 -1  0  1  1 -2  1  0  0]
 [-1  2  2 -2  0 -2  2  1 -1 -2 -1 -2  1 -2 -1 -2]
 [-1  0 -2  0 -1 -1 -1  1 -2  1 -1  2 -1  2  0 -2]
 [-1  0  2 -1  1 -1  0 -1  1  2  1 -1 -2  0 -1 -1]
 [ 1  1  1 -1  1 -1 -1  1 -2  0 -1  1  2  2  0 -1]
 [ 2  0  0  0  2  0 -2  0  1  2  0 -2  2  1 -2 -1]
 [-2 -2  2  0  1 -2  1  0  1  1 -2  1  0  1  2 -2]
 [-2  0  0 -2  2 -2 -1  2  2  0 -2 -2 -1  0  2  2]
 [-2 -2  0 -2  2  1 -2 -1  1 -1  2  2  2 -2  1  1]
 [-1  2  2  2  2 -2  2 -2  2  0 -1  1 -2  0 -2  2]
 [-2  0  2 -1 -2  0  1  1  0 -2  0 -1 -2 -1  1 -2]]
[[-0.10309449  0.03838499 -0.01185721  0.06333579  0.28106013  0.12425952
  -0.13370482 -0.03019248  0.09793995  0.20238186  0.17809111 -0.25099682
   0.14494882 -0.04634068 -0.017689